DELIMITER $$

USE pinf_pro$$

ALTER TABLE `dnevno_stanje_racuna`
CHANGE COLUMN `datum` `datum` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP$$

ALTER TABLE `racun_pravnog_lica`
CHANGE COLUMN `datum_otvaranja` `datum_otvaranja` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP$$

ALTER TABLE `kliring`
CHANGE COLUMN `datum` `datum` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP$$

ALTER TABLE `kursna_lista`
CHANGE COLUMN `datum` `datum` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP$$

ALTER TABLE `analitika_izvoda`
CHANGE COLUMN `datum_prijema` `datum_prijema` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP$$

ALTER TABLE `ukidanje`
CHANGE COLUMN `datum_ukidanja` `datum_ukidanja` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP$$
