version: '2'
services:
    pinf_pro-mysql:
        container_name: pinf_pro-mysql
        image: mysql:5.7.11
        # volumes:
        #     - ~/volumes/jhipster/pinf_pro/mysql/:/var/lib/mysql/
        environment:
            - MYSQL_USER=root
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
            - MYSQL_DATABASE=pinf_pro
        ports:
            - 3306:3306
        command: mysqld --lower_case_table_names=1 --skip-ssl
